version: '2'

services:
  ui:
    image: vinodsanthanam/ui 
    ports:
      - "5001"
    environment:
      - port=5001
      - api_base_url=http://192.168.99.110 
    networks:
      - back-tier
  ui_lb:
    image: vinodsanthanam/lb
    ports:
      - "80:80"
    environment:
      - constraint:node==ui-master
      - APP_NAME=ui
      - CONSUL_URL=${UI_KV_IP}:8500
    depends_on:
      - ui
    networks:
      - front-tier
networks:
  front-tier:
    driver: overlay
  back-tier:
    driver: overlay
