#!/bin/bash
echo "Usage:"
echo "./go -watch -- to watch for files"
echo "./go -start port -- to start local server for specific environment, defaults to dev"
echo "./go -docker -- to run the app in docker container on port 5000"
echo ""

npm install
bower install
rm -rf public
./node_modules/.bin/grunt 

if [ "$1" = "-watch" ]; then
  ./node_modules/.bin/grunt watch
elif [ "$1" = "-start" ]; then
    if [ "$2" != "" ]; then
      export api_base_url=$2
    else
      export api_base_url="http://localhost:8081"
    fi
    export port=5001
    npm start
fi

if [ "$1" = "-docker" ]; then
  docker build -t vinodsanthanam/ui .
  docker run -p 5000:5000 --env port=5000 --env api_base_url="http://192.168.1.37:8082" -d vinodsanthanam/ui 
fi

if [ "$1" = "-tag" ]; then
  docker build -t vinodsanthanam/ui .
  docker tag vinodsanthanam/ui vinodsanthanam/ui:2
  docker push vinodsanthanam/ui
fi
