#!/bin/bash

# https://botleg.com/stories/load-balancing-with-docker-swarm/

# create consul for storing kv pairs for the swarm
docker-machine create --driver virtualbox api-consul

export API_KV_IP=$( docker-machine ip api-consul)

eval $(docker-machine env api-consul)
docker run -d -p ${API_KV_IP}:8500:8500 -h api-consul --restart always gliderlabs/consul-server -bootstrap

#create master node
docker-machine create --driver virtualbox --swarm --swarm-master --swarm-discovery="consul://${API_KV_IP}:8500" --engine-opt="cluster-store=consul://${API_KV_IP}:8500" --engine-opt="cluster-advertise=eth1:2376" api-master
# create slave node
docker-machine create --driver virtualbox --swarm --swarm-discovery="consul://${API_KV_IP}:8500" --engine-opt="cluster-store=consul://${API_KV_IP}:8500" --engine-opt="cluster-advertise=eth1:2376" api-slave 

# change context to docker-machine
eval $(docker-machine env -swarm api-master)

# list all the docker containers
docker-compose ps

# creates the containers based on the docker-compose.yml file
docker-compose up -d

#scale the number of nodes running api to 4
docker-compose scale api=4

# list all the docker containers
docker-compose ps
