#!/bin/bash
SECONDS=0;
# https://botleg.com/stories/load-balancing-with-docker-swarm/

# create consul for storing kv pairs for the swarm
docker-machine create --driver virtualbox api-consul

export API_KV_IP=$( docker-machine ip api-consul)

eval $(docker-machine env api-consul)
docker run -d -p ${API_KV_IP}:8500:8500 -h api-consul --restart always gliderlabs/consul-server -bootstrap -client=0.0.0.0

#create master node
docker-machine create --driver virtualbox --swarm --swarm-master --swarm-discovery="consul://${API_KV_IP}:8500" --engine-opt="cluster-store=consul://${API_KV_IP}:8500" --engine-opt="cluster-advertise=eth1:2376" api-master
export API_MASTER_IP=$(docker-machine ssh api-master 'ifconfig eth1 | grep "inet addr:" | cut -d: -f2 | cut -d" " -f1')

# create slave node
docker-machine create --driver virtualbox --swarm --swarm-discovery="consul://${API_KV_IP}:8500" --engine-opt="cluster-store=consul://${API_KV_IP}:8500" --engine-opt="cluster-advertise=eth1:2376" api-slave 
export API_SLAVE_IP=$(docker-machine ssh api-slave 'ifconfig eth1 | grep "inet addr:" | cut -d: -f2 | cut -d" " -f1')

# setup registrator in master and slave nodes for it to register the ports and ip address with consul so that nginx can read the information from consul
# setup registrator in master
eval $(docker-machine env api-master)
docker run -d --name=registrator -h ${API_MASTER_IP} --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip ${API_MASTER_IP} consul://${API_KV_IP}:8500

# setup registrator in slave
eval $(docker-machine env api-slave)
docker run -d --name=registrator -h ${API_SLAVE_IP} --volume=/var/run/docker.sock:/tmp/docker.sock gliderlabs/registrator:latest -ip ${API_MASTER_IP} consul://${API_KV_IP}:8500


# change context to docker-machine in swarm mode
eval $(docker-machine env -swarm api-master)

# list all the docker containers
docker-compose ps

# creates the containers based on the docker-compose.yml file
docker-compose up -d

#scale the number of nodes running api to 4
docker-compose scale api=4

# list all the docker containers
docker-compose ps

duration=$SECONDS
echo "Time taken to finish creating the swarm $(($duration / 60)) minutes and $(($duration % 60)) "
