version: '2'

services:
  api:
    image: vinodsanthanam/api 
    ports:
      - "8082"
    environment:
      - api_port=8082
    networks:
      - back-tier

networks:
  back-tier:
    driver: overlay
