version: '2'

services:
  api:
    image: vinodsanthanam/api 
    ports:
      - "8083"
    environment:
      - api_port=8083
    networks:
      - front-tier
      - back-tier
  api_lb:
    image: vinodsanthanam/lb
    ports:
      - "80:80"
    environment:
      - constraint:node==api-master
      - APP_NAME=api
      - CONSUL_URL=${API_KV_IP}:8500
    depends_on:
      - api 
    networks:
      - front-tier
networks:
  front-tier:
    driver: overlay
  back-tier:
    driver: overlay
