#!/bin/bash

echo "Usage:"
echo "./go -- to run the api on local box"
echo "./go -docker -- to run the api on a docker container on port 8082"

npm install

if [ "$1" != "" ] && [ "$1" != "-docker" ]; then
  export api_port=$1
else
  export api_port=8081
fi

if [ "$1" = "-docker" ]; then
  docker build -t vinodsanthanam/api .
  docker run -p 8082:8082 --env api_port=8082 -d vinodsanthanam/api
  sleep 2
  curl http://localhost:8082/datetime
  docker push vinodsanthanam/api
  echo ""
else
  npm start
  curl http://localhost:8081/datetime
fi
